import { IItem } from '../models/item.model';

const mockItems: IItem[] = [
  {
    id: 0,
    beTitle: 'птушка',
    ltnTitle: 'ptuška',
    enTitle: 'bird',
    imagePath: './src/assets/img/cards-images/bird.png',
    soundPath: '',
    category: 'animals',
  },
  {
    id: 1,
    beTitle: 'кот',
    ltnTitle: 'kot',
    enTitle: 'cat',
    imagePath: './src/assets/img/cards-images/cat.png',
    soundPath: '',
    category: 'animals',
  },
  {
    id: 2,
    beTitle: 'жаба',
    ltnTitle: 'žaba',
    enTitle: 'frog',
    imagePath: './src/assets/img/cards-images/frog.png',
    soundPath: '',
    category: 'animals',
  },
  {
    id: 3,
    beTitle: 'карова',
    ltnTitle: 'karova',
    enTitle: 'cow',
    imagePath: './src/assets/img/cards-images/cow.png',
    soundPath: '',
    category: 'animals',
  },
  {
    id: 4,
    beTitle: 'леў',
    ltnTitle: 'leŭ',
    enTitle: 'lion',
    imagePath: './src/assets/img/cards-images/lion.png',
    soundPath: '',
    category: 'animals',
  },
  {
    id: 5,
    beTitle: 'малпа',
    ltnTitle: 'małpa',
    enTitle: 'monkey',
    imagePath: './src/assets/img/cards-images/monkey.png',
    soundPath: '',
    category: 'animals',
  },
  {
    id: 6,
    beTitle: 'свіння',
    ltnTitle: 'śvińnia',
    enTitle: 'pig',
    imagePath: './src/assets/img/cards-images/pig.png',
    soundPath: '',
    category: 'animals',
  },
  {
    id: 7,
    beTitle: 'тыгр',
    ltnTitle: 'tyhr',
    enTitle: 'tiger',
    imagePath: './src/assets/img/cards-images/tiger.png',
    soundPath: '',
    category: 'animals',
  },
  {
    id: 8,
    beTitle: 'воблака',
    ltnTitle: 'vobłaka',
    enTitle: 'cloud',
    imagePath: './src/assets/img/cards-images/cloud.png',
    soundPath: '',
    category: 'weather',
  },
  {
    id: 9,
    beTitle: 'холад',
    ltnTitle: 'choład',
    enTitle: 'cold',
    imagePath: './src/assets/img/cards-images/cold.png',
    soundPath: '',
    category: 'weather',
  },
  {
    id: 10,
    beTitle: 'спякота',
    ltnTitle: 'śpiakota',
    enTitle: 'heat',
    imagePath: './src/assets/img/cards-images/hot.png',
    soundPath: '',
    category: 'weather',
  },
  {
    id: 11,
    beTitle: 'вясёлка',
    ltnTitle: 'viasiołka',
    enTitle: 'rainbow',
    imagePath: './src/assets/img/cards-images/rainbow.png',
    soundPath: '',
    category: 'weather',
  },
  {
    id: 12,
    beTitle: 'дождж',
    ltnTitle: 'doždž',
    enTitle: 'rain',
    imagePath: './src/assets/img/cards-images/rain.png',
    soundPath: '',
    category: 'weather',
  },
  {
    id: 13,
    beTitle: 'сьнег',
    ltnTitle: 'śnieh',
    enTitle: 'snow',
    imagePath: './src/assets/img/cards-images/snow.png',
    soundPath: '',
    category: 'weather',
  },
  {
    id: 14,
    beTitle: 'навальніца',
    ltnTitle: 'navalnica',
    enTitle: 'thunderstorm',
    imagePath: './src/assets/img/cards-images/stormy.png',
    soundPath: '',
    category: 'weather',
  },
  {
    id: 15,
    beTitle: 'вецер',
    ltnTitle: 'viecier',
    enTitle: 'wind',
    imagePath: './src/assets/img/cards-images/wind.png',
    soundPath: '',
    category: 'weather',
  },
  {
    id: 16,
    beTitle: 'заплечнік',
    ltnTitle: 'zaplečnik',
    enTitle: 'backpack',
    imagePath: './src/assets/img/cards-images/backpack.png',
    soundPath: '',
    category: 'things',
  },
  {
    id: 17,
    beTitle: 'дошка',
    ltnTitle: 'doška',
    enTitle: 'blackboard',
    imagePath: './src/assets/img/cards-images/blackboard.png',
    soundPath: '',
    category: 'things',
  },
  {
    id: 18,
    beTitle: 'кніга',
    ltnTitle: 'kniha',
    enTitle: 'book',
    imagePath: './src/assets/img/cards-images/book.png',
    soundPath: '',
    category: 'things',
  },
  {
    id: 19,
    beTitle: 'калькулятар',
    ltnTitle: 'kalkulatar',
    enTitle: 'calculator',
    imagePath: './src/assets/img/cards-images/calculator.png',
    soundPath: '',
    category: 'things',
  },
  {
    id: 20,
    beTitle: 'глобус',
    ltnTitle: 'hłobus',
    enTitle: 'globe',
    imagePath: './src/assets/img/cards-images/globe.png',
    soundPath: '',
    category: 'things',
  },
  {
    id: 21,
    beTitle: 'ручка',
    ltnTitle: 'ručka',
    enTitle: 'pen',
    imagePath: './src/assets/img/cards-images/pen.png',
    soundPath: '',
    category: 'things',
  },
  {
    id: 22,
    beTitle: 'аловак',
    ltnTitle: 'ałovak',
    enTitle: 'pencil',
    imagePath: './src/assets/img/cards-images/pencil.png',
    soundPath: '',
    category: 'things',
  },
  {
    id: 23,
    beTitle: 'лінейка',
    ltnTitle: 'liniejka',
    enTitle: 'ruler',
    imagePath: './src/assets/img/cards-images/ruler.png',
    soundPath: '',
    category: 'things',
  },
  {
    id: 24,
    beTitle: 'ровар',
    ltnTitle: 'rovar',
    enTitle: 'bicycle',
    imagePath: './src/assets/img/cards-images/bicycle.png',
    soundPath: '',
    category: 'vehicles',
  },
  {
    id: 25,
    beTitle: 'аўтобус',
    ltnTitle: 'aŭtobus',
    enTitle: 'bus',
    imagePath: './src/assets/img/cards-images/bus.png',
    soundPath: '',
    category: 'vehicles',
  },
  {
    id: 26,
    beTitle: 'лодка',
    ltnTitle: 'łodka',
    enTitle: 'boat',
    imagePath: './src/assets/img/cards-images/boat.png',
    soundPath: '',
    category: 'vehicles',
  },
  {
    id: 27,
    beTitle: 'машына',
    ltnTitle: 'mašyna',
    enTitle: 'car',
    imagePath: './src/assets/img/cards-images/car.png',
    soundPath: '',
    category: 'vehicles',
  },
  {
    id: 28,
    beTitle: 'верталёт',
    ltnTitle: 'viertalot',
    enTitle: 'helicopter',
    imagePath: './src/assets/img/cards-images/helicopter.png',
    soundPath: '',
    category: 'vehicles',
  },
  {
    id: 29,
    beTitle: 'ракета',
    ltnTitle: 'rakieta',
    enTitle: 'rocket',
    imagePath: './src/assets/img/cards-images/rocket.png',
    soundPath: '',
    category: 'vehicles',
  },
  {
    id: 30,
    beTitle: 'скейтборд',
    ltnTitle: 'skiejtbord',
    enTitle: 'skateboard',
    imagePath: './src/assets/img/cards-images/skateboard.png',
    soundPath: '',
    category: 'vehicles',
  },
  {
    id: 31,
    beTitle: 'цягнік',
    ltnTitle: 'ciahnik',
    enTitle: 'train',
    imagePath: './src/assets/img/cards-images/train.png',
    soundPath: '',
    category: 'vehicles',
  },
];

export default mockItems;
